classdef UIViewController < YMicroscope.UIView
    %UIView Controller to control the UIView
    % Yao Zhao, 11/9/2015
    
    properties
        microscope_handle
        actions
    end
    
    methods
        function obj = UIViewController(microscope_handle)
            import YMicroscope.*
            obj@YMicroscope.UIView();
            obj.microscope_handle=microscope_handle;
            obj.actions=[ MicroscopeActionLive(...
                obj.microscope_handle,obj.imageaxis_handle,obj.hist_handle),...
                MicroscopeActionCapture(...
                obj.microscope_handle,obj.imageaxis_handle,obj.hist_handle),...
                MicroscopeActionSequenceZstack(...
                obj.microscope_handle,obj.imageaxis_handle,obj.hist_handle),...
                MicroscopeActionLiveFNet(...
                obj.microscope_handle,obj.imageaxis_handle,obj.hist_handle),...
                %                 MicroscopeActionSequenceMovieImage('movieimage',...
                %                 obj.microscope_handle,obj.imageaxis_handle),...
                %                 MicroscopeActionSequenceMovieStack('moviezstack',...
                %                 obj.microscope_handle,obj.imageaxis_handle),...
                ];
  
            % add controls
            for i=1:length(obj.actions)
                ir= floor((i-1)/4);
                ic= mod((i-1),4);
                obj.addControlButton(ic,ir,obj.actions(i));
            end
            
            % add refresh button for histogram
            obj.addHistRefreshButton(3,3);

            % add selectors
            obj.addControlSelector(0,2,'illumination','Illumination',...
                obj.microscope_handle);
            obj.addControlSelector(1,2,'roi','Camera ROI',...
                obj.microscope_handle.camera);
            obj.addControlSelector(0,3,'issaving','Save Captures',...
                obj.actions(2));
            obj.addControlSelector(1,3,'lockfocus','LiveFocus',...
                obj.actions(4));
            
            % add parameters
            obj.addParamCellWithExposure(0,0,'exposure','brightfield exposure(ms)',...
                obj.microscope_handle.lightsources(1), obj.microscope_handle.camera);
            obj.addParamCell(0,1,'intensity','brightfield intensity(1-10)',...
                obj.microscope_handle.lightsources(1));
            obj.addParamCellWithExposure(0,2,'exposure','fluorescent exposure(ms)',...
                obj.microscope_handle.lightsources(2), obj.microscope_handle.camera);
            obj.addParamCell(0,3,'intensity','fluorescent intensity(0-255)',...
                obj.microscope_handle.lightsources(2));
            try
            obj.addParamCellWithExposure(0,4,'exposure','473nm Laser Exposure(ms)',...
                obj.microscope_handle.lightsources(3), obj.microscope_handle.camera);
            obj.addParamCellWithExposure(0,5,'exposure','560nm Laser Exposure(ms)',...
                obj.microscope_handle.lightsources(4), obj.microscope_handle.camera);
            obj.addParamCell(0,6,'power','560nm Power(mW)',...
                obj.microscope_handle.lightsources(4));
            catch
                disp('Laser(s)=OFF')
                clc
            end
            obj.addParamCell(1,0,'zoffset','piezo center (volts)',...
                obj.microscope_handle.zstage);
            obj.addParamCell(1,1,'numstacks','number of stacks',...
                obj.microscope_handle.zstage);
            obj.addParamCell(1,2,'stepsize','step size (pixels)',...
                obj.microscope_handle.zstage);
            obj.addParamCell(2,0,'framerate','frame rate of camera (Hz)',...
                obj.microscope_handle.trigger);
            obj.addParamCell(2,1,'clockrate','sampling rate of clock (Hz)',...
                obj.microscope_handle.trigger);
%             obj.addParamCell(2,0,'moviecycles','number of movie cycles',...
%                 obj);
%             obj.addParamCell(2,1,'movieinterval','movie interval (mins)',...
%                 obj);
            obj.addParamCell(3,1,'focalplanecorrect','focal plane correction (pixel)',...
                obj.actions(4));

        end
        
        function delete(obj)
            for i = 1:length(obj.actions)
                delete(obj.actions(i))
            end
            obj.delete@YMicroscope.UIView();
        end
        
    end
    
    events
    end
    
end

